Objetivo

Realizar un análisis exploratorio de datos (EDA) sobre un conjunto de datos de medallas olímpicas utilizando Pandas. Este proyecto te permitirá aplicar los conceptos aprendidos sobre Series, DataFrames, limpieza de datos, operaciones básicas, filtrado y agregación en Pandas.

Consigna

Vas a trabajar con el conjunto de datos medallas.csv, que descargarás de la lección Proyecto del Día 6, que incluye información sobre las medallas de oro, plata, bronce y el total obtenido por cada país en los Juegos Olímpicos.

Vas a realizar una serie de tareas básicas, que te permitirán responder a las preguntas del cuestionario que encontrarás al final del día. Las tareas que realizarás son:

Cargar los Datos: Importar los datos desde el archivo CSV a un DataFrame de Pandas.
Exploración Inicial: Utilizar métodos básicos para explorar el tamaño, las columnas y los tipos de datos del DataFrame.
Limpieza de Datos: Identificar y manejar valores faltantes o incorrectos, especialmente en las columnas de medallas donde los valores faltantes indican cero medallas.
Análisis de Medallas por País: Realiza las operaciones que sean necesarias para identificar cuáles fueron los 3 países con más medallas en total. Vas a necesitar investigar los métodos de dataframe para encontrar cuál te permite ordenar los valores de mayor a menor o viceversa.
Análisis de Medallas Totales por País: Obtener un dataframe que contenga sólo los países que ganaron más de 10 medallas en total.
Una vez que hayas realizado estos pasos, HAZ UN PDF, que contenga las respuestas a los incisos planteados.

In [2]:
# Carga del archivo CSV a un DataFrame
import numpy as np
import pandas as pd

1. Creación del DataFrame

In [3]:
ruta = "C:/medallas.csv"
df = pd.read_csv(ruta)

df

     Oro  Plata  Bronce  Total          Pais
0    NaN    1.0     2.0      3     Argentina
1    NaN    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    NaN    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   NaN    1.0     NaN      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    NaN     2.0      5    Uzbekistan
92   1.0    3.0     NaN      4     Venezuela

[93 rows x 5 columns]

In [ ]:
2. Observaciones de los datos.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [5]:
df.head()

    Oro  Plata  Bronce  Total        Pais
0   NaN    1.0     2.0      3   Argentina
1   NaN    2.0     2.0      4     Armenia
2  17.0    7.0    22.0     46   Australia
3   1.0    1.0     5.0      7     Austria
4   NaN    3.0     4.0      7  Azerbaijan

In [6]:
df.isnull()

      Oro  Plata  Bronce  Total   Pais
0    True  False   False  False  False
1    True  False   False  False  False
2   False  False   False  False  False
3   False  False   False  False  False
4    True  False   False  False  False
..    ...    ...     ...    ...    ...
88   True  False    True  False  False
89  False  False   False  False  False
90  False  False   False  False  False
91  False   True   False  False  False
92  False  False    True  False  False

[93 rows x 5 columns]

In [7]:
nuevos_valores = {"Oro":0, 
                  "Plata":0,
                  "Bronce":0
                 }
df_rellenados = df.fillna(nuevos_valores)
df = df_rellenados
df

     Oro  Plata  Bronce  Total          Pais
0    0.0    1.0     2.0      3     Argentina
1    0.0    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    0.0    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   0.0    1.0     0.0      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    0.0     2.0      5    Uzbekistan
92   1.0    3.0     0.0      4     Venezuela

[93 rows x 5 columns]

In [ ]:
3. Top 3 paises con mas medallas

In [21]:
top3_paises = df.sort_values(by='Total', ascending = False).head(3)
top3_paises

     Oro  Plata  Bronce  Total                        Pais
25  39.0   41.0    33.0    113   Estados Unidos de America
72  38.0   32.0    18.0     88  Republica Popular de China
73   2.0   28.0    23.0     71                         ROC

4. Los países que tienen más de 10 medallas

In [22]:
mas_diez_medallas = df[df['Total'] > 10]
mas_diez_medallas

     Oro  Plata  Bronce  Total                        Pais
2   17.0    7.0    22.0     46                   Australia
11   7.0    6.0     8.0     21                      Brazil
14   7.0    6.0    11.0     24                      Canada
15   2.0    4.0     6.0     12              Chinese Taipei
19   7.0    3.0     5.0     15                        Cuba
20   4.0    4.0     3.0     11              Czech Republic
21   3.0    4.0     4.0     11                     Denmark
25  39.0   41.0    33.0    113   Estados Unidos de America
30   1.0   12.0    11.0     33                      France
32   1.0   11.0    16.0     37                     Germany
34  22.0   21.0    22.0     65                Gran Bretana
46  27.0   14.0    17.0     58                       Japon
60   1.0   12.0    14.0     36                 Netherlands
66   4.0    5.0     5.0     14                      Poland
72  38.0   32.0    18.0     88  Republica Popular de China
73   2.0   28.0    23.0     71                         ROC
81   3.0    8.0     6.0     17                       Spain
83   3.0    4.0     6.0     13                 Switzerland
87   2.0    2.0     9.0     13                      Turkey
90   1.0    6.0    12.0     19                     Ukraine